### PR TITLE
Support the 'import-name: true' setting of TSLint

### PR DESCRIPTION
**Pull request by kenchan0130**
It reflects the results of [this discussion](https://github.com/nwtgck/ts-copyable-npm/pull/8#issuecomment-455028076).

I adopted idea2 of https://github.com/nwtgck/ts-copyable-npm/pull/8#issuecomment-454719997

Related https://github.com/nwtgck/ts-copyable-npm/pull/8

### CODE REVIEW

**Comment by nwtgck** [comment]
@kenchan0130 Thank you very much for your PR!!
Ready to merge?

**Comment by kenchan0130** [comment]
@nwtgck 

Yes. If you'd like, please merge this PR.

Thank you.

**Comment by nwtgck** [comment]
I think this project should also use tslint and test in CI.

I have two options to use tslint in this project.
- option1: Using tslint is included in this PR
OR 
- option2: Using tslint can be another new PR

**Comment by kenchan0130** [comment]
I want to select 

> Using tslint can be another new PR.

this option.

But I can not try it right away.
Therefore, I think that it is good to unify the context if you may do nothing for this PR.

**Review by nwtgck — APPROVED** [review]
Thank you very much! LGTM 👍

**Comment by nwtgck** [comment]
@kenchan0130 Can I merge this?

**Comment by kenchan0130** [comment]
@nwtgck 

Yes you can.

**Comment by nwtgck** [comment]
@kenchan0130 After merging, I'll release 0.1.0.

**Comment by kenchan0130** [comment]
I think that it is better to introduce tslint for this project either way.

**Comment by nwtgck** [comment]
@kenchan0130 Thank you for your suggestion. I agree with your idea because this project may have other issues other than `import-name: true`.

Will you introduce tslint? or Should I introduce it?  What I want to do is to avoid a confliction of PRs.

**Pull request merged**
